
package wdsr.exercise3.hr.definitions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import wdsr.exercise3.hr.schemas.HolidayRequest;
import wdsr.exercise3.hr.schemas.HolidayResponse;
import wdsr.exercise3.hr.schemas.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HumanResource", targetNamespace = "http://exercise3.wdsr/hr/definitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HumanResource {


    /**
     * 
     * @param holidayRequest
     * @return
     *     returns wdsr.exercise3.hr.schemas.HolidayResponse
     */
    @WebMethod(operationName = "Holiday", action = "http://exercise3.wdsr/RequestHoliday")
    @WebResult(name = "HolidayResponse", targetNamespace = "http://exercise3.wdsr/hr/schemas", partName = "HolidayResponse")
    public HolidayResponse holiday(
        @WebParam(name = "HolidayRequest", targetNamespace = "http://exercise3.wdsr/hr/schemas", partName = "HolidayRequest")
        HolidayRequest holidayRequest);

}
